### ISSUE TITLE
SnapshotFileManager findFile and listFiles return null

### ISSUE THREAD

**Issue by nitehu** [K1rakishou/Fuck-Storage-Access-Framework#28]
Hi!
I'm creating a snapshot of a SAF directory, but after that calling findFile() and listFiles() on the returned FileManager return null even if the file exists.
It seems SnapshotFileManager starts tracking the files only after I call create on one.
Is this how this is supposed to work?
How can I use the SnapshotFileManager to list the files that were snapshotted?

**Comment by K1rakishou** [comment]
Is the file located in a sub directory or is it in the same directory you are creating a snapshot of? If it's in a sub directory you should use the `includeSubDirs=true` flag of the `createSnapshot()` method.

**Comment by nitehu** [comment]
Yes, I've set the includeSubDirs to true.
After debugging a bit, it seemed the snapshot was created, the FastFileSearchTree did contain the name of all directories and files, but all the "value" properties were null.
As I remember, this made findFile fail in [FastFileSearchTree line 458](https://github.com/K1rakishou/Fuck-Storage-Access-Framework/blob/78f802e3a58d8b538834a5cae481c3feab7075fc/fsaf/src/main/java/com/github/k1rakishou/fsaf/FastFileSearchTree.kt#L458), and listFiles fail in [SnapshotFileManager line 226](https://github.com/K1rakishou/Fuck-Storage-Access-Framework/blob/78f802e3a58d8b538834a5cae481c3feab7075fc/fsaf/src/main/java/com/github/k1rakishou/fsaf/manager/SnapshotFileManager.kt#L226). On both places the value was null.

So I'm not sure what did I miss, the code was just something like createSnapshot on the directory (which was selected by the user) with includeSubdirs=true, and then calling listFiles() on the returned SnapshotFileManager.

**Comment by K1rakishou** [comment]
Yeah, there was a bug when creating the snapshot. The input directory was not added into the snapshot's FastFileSearchTree which caused it's value to be null (when it's supposed to be a CachingDocumentFile) which in turn caused the children to not get processed. I'm gonna release the fix soon.

**Comment by K1rakishou** [comment]
Fixed in v1.1.1

**Comment by nitehu** [comment]
Thank you very much!
