### ISSUE TITLE
dependency for build.gradle doesn't seem correct

### ISSUE THREAD

**Issue by FrankDomburg** [K1rakishou/Fuck-Storage-Access-Framework#31]
Copy-pasting from readme.md doesn't give me what I expect, ie. access to FSAF.

Can't figure out what is wrong though.

**Comment by K1rakishou** [comment]
Do you have jitpack added to your gradle file? 
`maven { url 'https://jitpack.io' }`
Because this library is only released on jitpack.

**Comment by sixro** [comment]
Hi @FrankDomburg I added it to my project yesterday and it worked like a charm. The only thing I did a little bit differently is adding the jitpack to the `settings.gradle` under `dependencyResolutionManagement`. Like this:
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by FrankDomburg** [comment]
Thanks!

Op do 31 mrt. 2022 19:18 schreef Roberto Simoni ***@***.***>:

**Comment by FrankDomburg** [comment]
Just for other novices out there, I applied both, K1rakishou's comment in build.gradle (for the app), and sixro's comment as described.
