### ISSUE TITLE
Right way to share the path to DownloadManager...

### ISSUE THREAD

**Issue by sixro** [K1rakishou/Fuck-Storage-Access-Framework#32]
Hi and thanks for this great library.  
I have a question that I have not been able to answer looking at the code and README.md.  
I have been able to create a file in a directory selected by the user. At the end of the file creation, I want to notify the user using  `DownloadManager`. I am using this code:
```java
    val downloadManager = ctx.getSystemService(DOWNLOAD_SERVICE) as DownloadManager
    downloadManager.addCompletedDownload(
        filename,
        "dummy description",
        true,
        "text/plain",
        file!!.getFullPath(),
        fileManager.getLength(file),
        true
    )
```
where `file` is the file obtained by the creation (i have used the `fileManager.createFile` method).  
So, as you can see I am sharing the *fullpath* of the file.  
The problem is that when I scroll down the notifications and click on the related entry, I receive an error saying that "content:" are blocked. Instead, If I open the `Download` app and click on the entry, I can open it.  
Is there a way to obtain a real path without that `content:` or am I using DownloadManager in the wrong way?
Regards

**Comment by K1rakishou** [comment]
I have never worked with DownloadManager so I don't really know. But googling this issue it seems like it was deprecated on the recent android versions and apparently you need to use MediaStore now? https://stackoverflow.com/questions/57399849/downloadmanager-addcompleteddownload-deprecated-on-android-q
Maybe this is the problem?

**Comment by sixro** [comment]
Many thanks.
I'll play with it.
